version: '3.5'

services:
    decon:
        build: ../
        image: szybia/decon:latest
        depends_on:
            - redis

    tests:
        build: ./tests
        image: szybia/decon-tests:latest
        depends_on: 
            - decon


    redis:
        image: redis:6.0.6-alpine
